import { useState } from 'react'
import { generateArtifact } from '../api/client'
import type { DocumentIR, IRBlock } from '../api/client'
import { S, Spinner, ErrorBanner, SectionHeader } from '../components/ui'
import { FileDown, Plus, Trash2, FileText, Table2, List } from 'lucide-react'

const FORMATS = [
  { id: 'docx', label: 'DOCX', ext: 'docx', mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' },
  { id: 'xlsx', label: 'XLSX', ext: 'xlsx', mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
  { id: 'pptx', label: 'PPTX', ext: 'pptx', mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' },
]

const BLOCK_TYPES = ['heading1', 'heading2', 'paragraph', 'list', 'table', 'page_break']

function newBlock(type: string): IRBlock {
  if (type === 'list') return { block_type: 'list', items: ['Item 1', 'Item 2'] }
  if (type === 'table') return {
    block_type: 'table',
    rows: [
      [{ text: 'Column A' }, { text: 'Column B' }],
      [{ text: 'Value 1' }, { text: 'Value 2' }],
    ],
  }
  return { block_type: type, text: type === 'heading1' ? 'Section Title' : 'Paragraph text.' }
}

export default function Artifacts() {
  const [title, setTitle] = useState('My Report')
  const [author, setAuthor] = useState('NovaMindd')
  const [format, setFormat] = useState('docx')
  const [blocks, setBlocks] = useState<IRBlock[]>([
    { block_type: 'heading1', text: 'Executive Summary' },
    { block_type: 'paragraph', text: 'This report was generated by NovaMindd.' },
    { block_type: 'heading2', text: 'Findings' },
    { block_type: 'list', items: ['Finding 1: Normal operations', 'Finding 2: Scheduled maintenance due'] },
  ])
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')
  const [generated, setGenerated] = useState(false)

  const addBlock = (type: string) => setBlocks(prev => [...prev, newBlock(type)])
  const removeBlock = (i: number) => setBlocks(prev => prev.filter((_, idx) => idx !== i))

  const updateBlock = (i: number, field: string, value: string) => {
    setBlocks(prev => prev.map((b, idx) => idx === i ? { ...b, [field]: value } : b))
  }

  const updateListItem = (bi: number, ii: number, value: string) => {
    setBlocks(prev => prev.map((b, idx) => {
      if (idx !== bi) return b
      const items = [...(b.items ?? [])]
      items[ii] = value
      return { ...b, items }
    }))
  }

  const handleGenerate = async () => {
    if (!title.trim()) return
    setGenerating(true)
    setError('')
    setGenerated(false)
    try {
      const ir: DocumentIR = { title, author, blocks, metadata: {}, evidence_refs: [] }
      const blob = await generateArtifact(format, ir)
      const fmt = FORMATS.find(f => f.id === format)!
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${title.replace(/\s+/g, '_')}.${fmt.ext}`
      a.click()
      URL.revokeObjectURL(url)
      setGenerated(true)
    } catch (e: any) {
      setError(e?.response?.data?.detail ?? 'Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  const blockIcon = (type: string) => {
    if (type.startsWith('heading')) return <FileText size={12} />
    if (type === 'table') return <Table2 size={12} />
    if (type === 'list') return <List size={12} />
    return <FileText size={12} />
  }

  return (
    <div>
      <SectionHeader title="Artifacts" subtitle="Build a document IR and generate DOCX, XLSX, or PPTX" />

      {error && <ErrorBanner message={error} />}

      <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: 24, alignItems: 'start' }}>

        {/* ── Builder ── */}
        <div>
          <div style={{ ...S.card, marginBottom: 16 }}>
            <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--color-text)', marginBottom: 16 }}>Document Settings</h3>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 }}>
              <div>
                <label style={S.label}>Title</label>
                <input value={title} onChange={e => setTitle(e.target.value)} style={S.input} />
              </div>
              <div>
                <label style={S.label}>Author</label>
                <input value={author} onChange={e => setAuthor(e.target.value)} style={S.input} />
              </div>
            </div>

            <div>
              <label style={S.label}>Output Format</label>
              <div style={{ display: 'flex', gap: 10 }}>
                {FORMATS.map(f => (
                  <button
                    key={f.id}
                    onClick={() => setFormat(f.id)}
                    style={{
                      flex: 1,
                      padding: '10px',
                      borderRadius: 8,
                      border: `2px solid ${format === f.id ? 'var(--color-accent)' : 'var(--color-border)'}`,
                      background: format === f.id ? 'rgba(99,102,241,0.12)' : 'var(--color-surface2)',
                      color: format === f.id ? 'var(--color-accent-hover)' : 'var(--color-muted)',
                      fontWeight: format === f.id ? 700 : 400,
                      cursor: 'pointer',
                      fontSize: 13,
                    }}
                  >
                    {f.label}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Blocks */}
          <div style={{ marginBottom: 12, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--color-text)' }}>
              Content Blocks ({blocks.length})
            </h3>
          </div>

          {blocks.map((block, i) => (
            <div key={i} style={{
              ...S.cardSm, marginBottom: 10,
              borderLeft: `3px solid var(--color-accent)`,
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: 'var(--color-muted)' }}>
                  {blockIcon(block.block_type)}
                  <code style={{ fontSize: 11, color: 'var(--color-accent-hover)' }}>{block.block_type}</code>
                </div>
                <button
                  onClick={() => removeBlock(i)}
                  style={{ ...S.btnGhost, padding: '4px 8px', fontSize: 11 }}
                >
                  <Trash2 size={11} />
                </button>
              </div>

              {(block.block_type !== 'list' && block.block_type !== 'table' && block.block_type !== 'page_break') && (
                <input
                  value={block.text ?? ''}
                  onChange={e => updateBlock(i, 'text', e.target.value)}
                  style={S.input}
                  placeholder="Content…"
                />
              )}

              {block.block_type === 'list' && (
                <div>
                  {(block.items ?? []).map((item, ii) => (
                    <input
                      key={ii}
                      value={item}
                      onChange={e => updateListItem(i, ii, e.target.value)}
                      style={{ ...S.input, marginBottom: 6 }}
                      placeholder={`Item ${ii + 1}`}
                    />
                  ))}
                </div>
              )}

              {block.block_type === 'table' && (
                <div style={{ fontSize: 12, color: 'var(--color-muted)' }}>
                  Table: {block.rows?.length ?? 0} row(s) × {block.rows?.[0]?.length ?? 0} column(s)
                </div>
              )}

              {block.block_type === 'page_break' && (
                <div style={{ fontSize: 12, color: 'var(--color-muted)', textAlign: 'center' }}>── page break ──</div>
              )}
            </div>
          ))}

          {/* Add block buttons */}
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 4 }}>
            {BLOCK_TYPES.map(bt => (
              <button
                key={bt}
                onClick={() => addBlock(bt)}
                style={{ ...S.btnGhost, padding: '6px 12px', fontSize: 12 }}
              >
                <Plus size={12} /> {bt}
              </button>
            ))}
          </div>
        </div>

        {/* ── Preview / Generate ── */}
        <div style={{ position: 'sticky', top: 24 }}>
          <div style={S.card}>
            <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--color-text)', marginBottom: 16 }}>
              Document Preview
            </h3>
            <div style={{
              background: 'var(--color-surface2)',
              border: '1px solid var(--color-border)',
              borderRadius: 8,
              padding: 16,
              maxHeight: 420,
              overflowY: 'auto',
              marginBottom: 16,
              fontSize: 13,
              lineHeight: 1.7,
            }}>
              <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 12, color: 'var(--color-text)' }}>{title || 'Untitled'}</div>
              <div style={{ fontSize: 11, color: 'var(--color-muted)', marginBottom: 16 }}>Author: {author}</div>
              {blocks.map((b, i) => {
                if (b.block_type === 'heading1') return <div key={i} style={{ fontWeight: 700, fontSize: 15, marginTop: 14, marginBottom: 6, color: 'var(--color-text)' }}>{b.text}</div>
                if (b.block_type === 'heading2') return <div key={i} style={{ fontWeight: 600, fontSize: 13.5, marginTop: 12, marginBottom: 5, color: 'var(--color-text)' }}>{b.text}</div>
                if (b.block_type === 'paragraph') return <p key={i} style={{ margin: '0 0 10px', color: 'var(--color-muted)' }}>{b.text}</p>
                if (b.block_type === 'list') return <ul key={i} style={{ paddingLeft: 18, margin: '0 0 10px', color: 'var(--color-muted)' }}>{(b.items ?? []).map((it, j) => <li key={j} style={{ marginBottom: 3 }}>{it}</li>)}</ul>
                if (b.block_type === 'table') return <div key={i} style={{ fontSize: 11, color: 'var(--color-muted)', margin: '8px 0', fontStyle: 'italic' }}>[Table: {b.rows?.length} rows]</div>
                if (b.block_type === 'page_break') return <hr key={i} style={{ border: 'none', borderTop: '1px dashed var(--color-border)', margin: '12px 0' }} />
                return null
              })}
            </div>

            <button
              style={{ ...S.btn, width: '100%', justifyContent: 'center', padding: '12px' }}
              onClick={handleGenerate}
              disabled={!title.trim() || generating || blocks.length === 0}
            >
              {generating ? <Spinner size={15} /> : <FileDown size={15} />}
              {generating ? 'Generating…' : `Generate ${format.toUpperCase()}`}
            </button>

            {generated && (
              <div style={{
                marginTop: 12, padding: '10px 14px', borderRadius: 8,
                background: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.25)',
                fontSize: 13, color: '#10b981', textAlign: 'center',
              }}>
                ✓ Downloaded successfully
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
